"""empty message

Revision ID: 337b0e69d062
Revises: b64b4a0db44b
Create Date: 2024-08-14 19:45:18.312896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '337b0e69d062'
down_revision = 'b64b4a0db44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bind_lane', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_bind_lane', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
