"""empty message

Revision ID: 87625c907c9a
Revises: decfde6c612f
Create Date: 2024-08-14 15:01:43.121711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87625c907c9a'
down_revision = 'decfde6c612f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_env', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_env', schema=None) as batch_op:
        batch_op.drop_column('update_time')

    # ### end Alembic commands ###
