"""empty message

Revision ID: b64b4a0db44b
Revises: fedb692322f5
Create Date: 2024-08-14 17:05:39.825996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64b4a0db44b'
down_revision = 'fedb692322f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_env', schema=None) as batch_op:
        batch_op.drop_index('service_env_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_env', schema=None) as batch_op:
        batch_op.create_index('service_env_name', ['service_env_name'], unique=True)

    # ### end Alembic commands ###
