"""empty message

Revision ID: decfde6c612f
Revises: 
Create Date: 2024-08-14 14:57:59.583579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decfde6c612f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_name', sa.String(length=80), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('build_image_name', sa.String(length=1024), nullable=False),
    sa.Column('main_git_url', sa.String(length=1024), nullable=False),
    sa.Column('main_artifact_url', sa.String(length=1024), nullable=False),
    sa.Column('build_command', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_name')
    )
    op.create_table('artifact_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('artifact_name', sa.String(length=80), nullable=False),
    sa.Column('artifact_version', sa.String(length=80), nullable=False),
    sa.Column('main_git_commit_id', sa.String(length=80), nullable=False),
    sa.Column('main_git_commit_title', sa.String(length=120), nullable=False),
    sa.Column('main_git_branch', sa.String(length=120), nullable=False),
    sa.Column('build_url', sa.String(length=1024), nullable=False),
    sa.Column('artifact_url', sa.String(length=1024), nullable=False),
    sa.Column('artifact_tag', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_version')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=80), nullable=False),
    sa.Column('main_git_url', sa.String(length=1024), nullable=False),
    sa.Column('main_artifact_url', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=80), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('service_tree_name', sa.String(length=80), nullable=False),
    sa.Column('attributes', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('service_deploy_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_env_name', sa.String(length=80), nullable=False),
    sa.Column('service_name', sa.String(length=80), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('creator', sa.String(length=80), nullable=False),
    sa.Column('attributes', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_env_name')
    )
    op.create_table('service_env_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_env_lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_env_name', sa.String(length=80), nullable=False),
    sa.Column('lane_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_env_name', 'lane_name', name='_service_env_name_lane_name_uc')
    )
    op.create_table('service_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_tree_name', sa.String(length=80), nullable=False),
    sa.Column('parent_service_tree_name', sa.String(length=80), nullable=False),
    sa.Column('attributes', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_tree_name')
    )
    op.create_table('user_bind_lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('lane_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bind_lane')
    op.drop_table('service_tree')
    op.drop_table('service_env_lane')
    op.drop_table('service_env_cluster')
    op.drop_table('service_env')
    op.drop_table('service_deploy_history')
    op.drop_table('service')
    op.drop_table('project')
    op.drop_table('config')
    op.drop_table('artifact_version')
    op.drop_table('artifact')
    # ### end Alembic commands ###
